// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYJ90uRUGxUvVRO4vgTDZANQ9XHhDza4',
    appId: '1:1097016010600:web:4d22acd7f264e749b598dd',
    messagingSenderId: '1097016010600',
    projectId: 'carrymark-a941b',
    authDomain: 'carrymark-a941b.firebaseapp.com',
    storageBucket: 'carrymark-a941b.firebasestorage.app',
    measurementId: 'G-LDRHRS1K53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJd_GXw2hMpMjYS_BMEFe3l29v6S3odj4',
    appId: '1:1097016010600:android:0902eb9d3547c866b598dd',
    messagingSenderId: '1097016010600',
    projectId: 'carrymark-a941b',
    storageBucket: 'carrymark-a941b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGe0vqR4hBihG0GbTtKSUdR0UAeLaE7N4',
    appId: '1:1097016010600:ios:10ed3a6599d3f66ab598dd',
    messagingSenderId: '1097016010600',
    projectId: 'carrymark-a941b',
    storageBucket: 'carrymark-a941b.firebasestorage.app',
    iosBundleId: 'com.example.carrymarkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGe0vqR4hBihG0GbTtKSUdR0UAeLaE7N4',
    appId: '1:1097016010600:ios:10ed3a6599d3f66ab598dd',
    messagingSenderId: '1097016010600',
    projectId: 'carrymark-a941b',
    storageBucket: 'carrymark-a941b.firebasestorage.app',
    iosBundleId: 'com.example.carrymarkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzYJ90uRUGxUvVRO4vgTDZANQ9XHhDza4',
    appId: '1:1097016010600:web:4e0c6a6035929e1fb598dd',
    messagingSenderId: '1097016010600',
    projectId: 'carrymark-a941b',
    authDomain: 'carrymark-a941b.firebaseapp.com',
    storageBucket: 'carrymark-a941b.firebasestorage.app',
    measurementId: 'G-DMYCH3BYNQ',
  );
}
